In [7]:
import numpy as np

1.) Create a NumPy array of integers from 1 to 10.

In [ ]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

2.) Create a 2x3 NumPy array filled with zeros.

In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

3.) Create a NumPy array of even numbers from 2 to 20.

In [ ]:
np.arange(2,21,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

4.)Given two NumPy arrays, arr1 = np.array([1, 2, 3]) and arr2 = np.array([4, 5, 6]), perform element-wise addition, subtraction, multiplication, and division between the two arrays.

In [ ]:
arr1=np.array([1,2,3])
arr1


array([1, 2, 3])

In [ ]:
arr2=np.array([4,5,6])
arr2


array([4, 5, 6])

In [ ]:
arr3=arr1+arr2
arr3

array([5, 7, 9])

In [ ]:
arr4=arr1-arr2
arr4

array([-3, -3, -3])

In [ ]:
arr5=arr1*arr2
arr5

array([ 4, 10, 18])

In [ ]:
arr6=arr1/arr2
arr6

array([0.25, 0.4 , 0.5 ])

5.) Compute the mean, median, and standard deviation of a NumPy array containing 100 random numbers.

In [31]:
arr4=np.random.rand(100)

In [32]:
arr4

array([0.0154298 , 0.7577385 , 0.84667635, 0.8856286 , 0.0756722 ,
       0.42879826, 0.01490343, 0.04157269, 0.09913708, 0.20774037,
       0.36710029, 0.32695078, 0.22126144, 0.88131501, 0.16658361,
       0.69914898, 0.05201696, 0.77767106, 0.58165781, 0.21935692,
       0.86639074, 0.34359051, 0.33239378, 0.83337512, 0.49346717,
       0.68114631, 0.94286487, 0.02306987, 0.28613162, 0.30296603,
       0.10193847, 0.41575781, 0.88112435, 0.94216525, 0.10004957,
       0.74938226, 0.51161877, 0.4607247 , 0.66745865, 0.63395051,
       0.47442495, 0.88446598, 0.6537878 , 0.44159061, 0.77365598,
       0.86627324, 0.48023118, 0.04246178, 0.16078896, 0.38921601,
       0.4014356 , 0.34623842, 0.8471683 , 0.52987124, 0.65371995,
       0.81264197, 0.4445075 , 0.28737985, 0.86236236, 0.34320478,
       0.91065785, 0.81496133, 0.30623001, 0.85343539, 0.25701625,
       0.31054461, 0.73061489, 0.58179352, 0.44463594, 0.79481138,
       0.95579034, 0.68819322, 0.07726409, 0.8118219 , 0.42490

In [ ]:
arr5=arr4.mean()
arr5

0.5516581141218442

6.) Reshape a 1D NumPy array of 12 random elements into a 2D array with a shape of (3, 4).

In [ ]:
arr6=np.random.randint(0,20,12)
arr6

array([11,  8,  7,  3,  9,  0,  5,  1,  0, 13, 19, 12])

In [ ]:
arr7=arr6.reshape(3,4)
arr7

array([[11,  8,  7,  3],
       [ 9,  0,  5,  1],
       [ 0, 13, 19, 12]])

7.) Given a NumPy array arr = np.array([1, 2, 3, 4, 5]), square each element in the array using NumPy functions.

In [ ]:
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [ ]:
np.square(arr)

array([ 1,  4,  9, 16, 25])

8.) Create a 5x5 identity matrix using NumPy.

In [ ]:
arr=np.eye(5,5)
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

9.) Calculate the dot product of two NumPy arrays, a = np.array([1, 2, 3]) and b = np.array([4, 5, 6]).

In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])
a.dot(b)


32

10.) Find the index of the maximum value and the index of the minimum value in a NumPy array.

In [ ]:
arr8=np.arange(1,50,2)
arr8
arr8.argmax()



24

In [ ]:
arr8.argmin()

0

11.) Concatenate two random NumPy arrays horizontally and vertically.

In [ ]:
a=np.random.rand(3,4)
a




array([[0.75535409, 0.87147623, 0.1298756 , 0.63616089],
       [0.68108772, 0.11804329, 0.22954996, 0.5855338 ],
       [0.62797779, 0.18543105, 0.04391115, 0.14239775]])

In [ ]:
b=np.random.rand(3,4)
b


array([[0.05077729, 0.03600175, 0.69437185, 0.65914706],
       [0.60023037, 0.82134384, 0.07637072, 0.46399997],
       [0.2986836 , 0.19165744, 0.65877446, 0.83347203]])

In [ ]:
np.concatenate([a,b])

array([[0.75535409, 0.87147623, 0.1298756 , 0.63616089],
       [0.68108772, 0.11804329, 0.22954996, 0.5855338 ],
       [0.62797779, 0.18543105, 0.04391115, 0.14239775],
       [0.05077729, 0.03600175, 0.69437185, 0.65914706],
       [0.60023037, 0.82134384, 0.07637072, 0.46399997],
       [0.2986836 , 0.19165744, 0.65877446, 0.83347203]])

In [ ]:
np.concatenate((a,b),axis=1)

array([[0.75535409, 0.87147623, 0.1298756 , 0.63616089, 0.05077729,
        0.03600175, 0.69437185, 0.65914706],
       [0.68108772, 0.11804329, 0.22954996, 0.5855338 , 0.60023037,
        0.82134384, 0.07637072, 0.46399997],
       [0.62797779, 0.18543105, 0.04391115, 0.14239775, 0.2986836 ,
        0.19165744, 0.65877446, 0.83347203]])

12.)Given a 2D NumPy array, calculate the sum of each row and each column separately

In [11]:
arr=np.arange(1,17).reshape(4,4)
print(arr)
print("Sum of each column is",np.sum(arr,axis=0))
print("Sum of each row is",np.sum(arr,axis=1))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Sum of each column is [28 32 36 40]
Sum of each row is [10 26 42 58]


13.)Find the common elements between two NumPy arrays.

In [15]:
a=np.array([[4,9],[5,8],[1,7]])
b=np.array([[3,9],[5,2],[6,7]])
c=np.intersect1d(a,b)
print("the common elements between a and b are",c)

the common elements between a and b are [5 7 9]


14.) Replace all negative values in a NumPy array with zeros.

In [16]:
x=np.array([1,2,3,-4,-5,-6])
x[x<0]=0
x

array([1, 2, 3, 0, 0, 0])

15.)Create a NumPy array with random integers between 1 and 100 and then
sort it in ascending order.

In [19]:
arr1=np.random.randint(1,101,100)
arr1.sort()
arr1

array([  1,   2,   2,   2,   4,   6,   8,  11,  11,  12,  12,  14,  14,
        15,  17,  17,  18,  19,  21,  21,  24,  24,  28,  28,  28,  30,
        31,  32,  32,  33,  34,  37,  37,  38,  38,  40,  40,  41,  42,
        42,  44,  44,  44,  45,  49,  52,  52,  52,  53,  53,  53,  54,
        54,  54,  54,  55,  55,  56,  56,  56,  56,  57,  58,  58,  58,
        58,  58,  59,  62,  63,  63,  66,  67,  67,  71,  73,  74,  75,
        76,  76,  78,  79,  81,  82,  83,  84,  85,  85,  85,  88,  88,
        90,  91,  91,  93,  93,  95,  95,  97, 100])

16.) Calculate the element-wise absolute difference between two NumPy
arrays

In [21]:
a=np.array([1,2,3,4,5,])
b=np.array([6,8,10,12,14])
c=np.absolute(a-b)
print(c)

[5 6 7 8 9]


17.) Given a 2D NumPy array, extract the first row and the last column.

In [23]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
firstrow=arr[0]
lastcol=arr[:,[-1]]
print(firstrow)
print(lastcol)

[1 2 3]
[[3]
 [6]
 [9]]


18.) Slice a 1D NumPy array to get every other element.

In [25]:
a=np.array([1,2,3,4,5])
x=a[0:len(a)+1]
print(x)

[1 2 3 4 5]


19.)
Given a 2D NumPy array, extract a subarray consisting of the central 2x2
elements.

In [29]:
arr=np.array([[10,1,14,16,18,20],[22,24,26,28,30,32],[34,36,38,40,42,44],[46,48,50,52,54,56],[58,60,62,64,66,68],[70,72,74,76,78,80]])
x=arr[2:4,[2,3]]
print(arr)
print("central 2x2 elements include\n",x)

[[10  1 14 16 18 20]
 [22 24 26 28 30 32]
 [34 36 38 40 42 44]
 [46 48 50 52 54 56]
 [58 60 62 64 66 68]
 [70 72 74 76 78 80]]
central 2x2 elements include
 [[38 40]
 [50 52]]


20.) Reverse a 1D NumPy array using slicing.

In [30]:
a=np.array([1,2,3,4,5])
x=a[::-1]
x

array([5, 4, 3, 2, 1])